### ISSUE TITLE
Mapping "Media ratings" results in errors on import

### ISSUE THREAD

**Issue by m4olivei** [Lullabot/media_mpx#111]
If I map the "Media ratings" field, the on import I get the following error:

```
 $ drush queue:run media_mpx_notification
[error] Object of class Lullabot\Mpx\DataService\Media\Rating could not be converted to string schema.inc:229 
 [error]  E_RECOVERABLE_ERROR encountered; aborting. To ignore recoverable errors, run again with --no-halt-on-error
```

Looks like this is b/c the ratings property on the MPX Media object is itself an object of type `\Lullabot\Mpx\DataService\Media\Rating`, which Drupal doesn't know what to do with.

**Comment by m4olivei** [comment]
I think for a lot of use cases, a simple `__toString` implementation would suffice to correct the issue, eg. 

```
public function __toString() {
  return $this->getRating();
}
```

If that doesn't meet the use case, for example the video has ratings in different schemes that Drupal needs to care about, or the sub ratings are important, then that probably puts you into custom import event listener territory? Unless we implemented a custom field type for rating, or exposed the different properties of a Rating object for mapping?

**Comment by deviantintegral** [comment]
For `MediaFiles`, we have specific support for the first file. Perhaps something similar would work for Ratings? Perhaps even a common use case of "this type of rating from the rating object", hardcoded as an available metadata property: https://github.com/Lullabot/media_mpx/blob/8.x-1.x/src/Plugin/media/Source/Media.php#L268-L271

It's moments like these I really wish PHP shipped with a `ToStringInterface` so we could check for that to reduce complex objects.

**Comment by m4olivei** [comment]
I think that could work. MPX documents a specific list of supported ratings schemes:

https://docs.theplatform.com/help/media-media-ratings#Media.ratings-Contentratingsystemssupportedbympx

The list is long though, it would definitely clutter the mapping interface. Maybe that doesn't matter though.

**Comment by deviantintegral** [comment]
It would be straight forward to add support for all of the content rating systems in that table, but not the subratings. Do you know if you need the subrating information? I think the mapping UI is already huge, but Drupal controls that so I think it's OK to leave as is.

If you need subratings, perhaps the toString() is good enough, given that the docs show the XML version is an almost-comma-separated list of all ratings like `tv-ma v, l, s` where the last three are the subratings.

**Comment by m4olivei** [comment]
We don't _need_ the sub-ratings, eg. they aren't used, however historically they were ingested as a separate field. Probably `toString()` would be good for some and not for others, so I'm leaning toward adding the mappings.

I'm in a time crunch to make this work ATM, so I'm going to implement an import event listener first, and then try to get back and work on this as a general solution.
