### ISSUE TITLE
Call to a member function getSource() on Null ... PlayerFormatter.php

### ISSUE THREAD

**Issue by edutrul** [Lullabot/media_mpx#120]
I installed https://www.drupal.org/project/readonly_field_widget
and configured to `mpx_video_17` form display (I changed all fields to READ ONLY and getting below error:
![image](https://user-images.githubusercontent.com/1582129/57534187-1a9c6a80-7305-11e9-9782-c4d79ccafc3b.png)

I don't think the issue may come directly to readonly_field_widget.
My proposal fix is to add defensive programming(make sure the entity object exists!)

**Comment by m4olivei** [comment]
@edutrul Try @salvamomo's suggestion from https://github.com/nbc-bravo/drupal-media_mpx/pull/21#discussion_r282913958. I believe that will lower the cognitive complexity as code climate sees it. I also agree with @salvamomo that it's a nice approach for cleaner diff.

**Comment by deviantintegral** [comment]
Looks like this is done!
