### ISSUE TITLE
TypeError: Argument 1 passed to ConcreteDateTime must be instance of DateTime

### ISSUE THREAD

**Issue by edutrul** [Lullabot/media_mpx#134]
When trying to execute below code:

```
/**
 * Implements hook_ENTITY_TYPE_access().
 */
function mymodule_node_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity instanceof NodeInterface && $operation == 'view' &&
    $entity->bundle() == 'a_content_type') {
    if ($entity->hasField('field_mpx') && !$entity->get('field_mpx')->isEmpty()) {
      /** @var \Drupal\media_mpx\Access\MediaAvailableAccess $access */
      $access = \Drupal::service('media_mpx.media_available_access');
      $media = $entity->field_mpx->entity;
      return $access->view($media, $account);
    }
  }
  return AccessResult::neutral();
}

```
And I go to a node where bundle is `a_content_type` then I get this fatal error:

The website encountered an unexpected error. Please try again later.
TypeError: Argument 1 passed to Lullabot\Mpx\DataService\DateTime\ConcreteDateTime::__construct() must be an instance of DateTime, boolean given, called in /var/lib/tugboat/web/modules/contrib/media_mpx/src/Access/MediaAvailableAccess.php on line 209 in Lullabot\Mpx\DataService\DateTime\ConcreteDateTime->__construct() (line 15 of /var/lib/tugboat/vendor/lullabot/mpx-php/src/DataService/DateTime/ConcreteDateTime.php).

I shouldn't get that error.

**Comment by juampynr** [comment]
Merged #135.
