### ISSUE TITLE
Convert availableDate and  expirationDate to DateTime fields

### ISSUE THREAD

**Issue by salvamomo** [Lullabot/media_mpx#141]
From:  https://github.com/Lullabot/media_mpx/pull/140#pullrequestreview-257492323

> I think there's actually a different bug at play here:
> https://github.com/Lullabot/media_mpx/blame/fa92229b30a1079d81a742a0af270cd2a6b02279/src/Plugin/media/Source/MediaSourceBase.php#L265-L269
> 
> That section wasn't intended to be added to this repository (oops past Andrew!). In summary, during migration we missed converting int fields to date / time fields (which are better because they are explicit about time zones). As a workaround, we patched in formatting the dates as a timestamp.
> 
> At this point, we could either go all-in and support timestamp fields everywhere (though we should also support mapping to date time fields), or roll that back and update the migration to convert the field types and data.

Whatever path is taken here (looks like simply "let's support as well timestamp fields and do nothing" is feasible as well), existing sites might be already using a timestamp, so it seems sensible to at least support that in the `MediaAvailableAccess` class checks. (Support implemented at https://github.com/Lullabot/media_mpx/pull/140). The alternative is that those sites are updated to move those fields to `DateTime` type.

**Comment by deviantintegral** [comment]
I would lean towards sticking with a single date-time field type (time zones are good!) but there's been enough confusion around this I could be persuaded otherwise.

**Comment by m4olivei** [comment]
Both Ukids and Bravo / Oxygen / Syfy use timestamp dates. It's not worth the effort to convert them to DateTime. Closing.
