### ISSUE TITLE
You have requested a non-existent service "plugin.manager.migrate.cckfield". 

### ISSUE THREAD

**Issue by lokisho** [Lullabot/media_mpx#165]
In a drupal 9 site after enabling the module and ran 
```
vendor/bin/drush migrate:upgrade --legacy-db-key='migrate' --legacy-root=PATH --configure-only
```
I'm getting this error
```
You have requested a non-existent service "plugin.manager.migrate.cckfield". Did you mean one of these: "plugin.manager.migrate.source", "plugin.m  
  anager.migration", "plugin.manager.migrate.process", "plugin.manager.migrate.destination", "plugin.manager.migrate.id_map", "plugin.manager.migrat  
  e.field", "plugin.manager.image.effect", "plugin.manager.views.field"? 
```
that seems to be originated here https://github.com/Lullabot/media_mpx/blob/8.x-1.x/src/Plugin/migrate/MpxItemDeriver.php#L90
not sure how to resolve this

**Comment by deviantintegral** [comment]
@m4olivei it looks like this may have slipped through our Drupal 9 upgrade work: https://www.drupal.org/node/2751897

Removed for real in https://www.drupal.org/project/drupal/issues/3088480.

I'm a little confused as to why we were using that service, given we were upgrading from 7 to 8, not 6 to 8. Perhaps we should have been using something else entirely?

**Comment by m4olivei** [comment]
Ooof, I haven't looked at that class in a long time. I'll need to get reaquinted with this. I'll have a closer look tomorrow.

**Comment by m4olivei** [comment]
> I'm a little confused as to why we were using that service, given we were upgrading from 7 to 8, not 6 to 8. Perhaps we should have been using something else entirely?

According to the change record (emphasis mine):

> The Drupal 8 migration system initially had plugins and classes supporting field migration from Drupal 6 incorporating "Cck" in their names - as of #2631736: Cckfield Plugins must distinguish core versions, **this support is largely shared with the Drupal 7 migrations, where "Cck" is a misnomer at best**. To better reflect the general nature of these plugins and classes, they are being renamed to use (only) "Field" in their names. The "Cck" names are deprecated as of Drupal 8.3.2 - please update any references to these names.

So seems like the CCK naming just over stayed it's welcome. Oddly, that service injects both the CCK service and the one meant to replace it: https://github.com/Lullabot/media_mpx/blob/8.x-1.x/src/Plugin/migrate/MpxItemDeriver.php#L90-L91.

I think we can just replace references to the CCK one (`plugin.manager.migrate.cckfield'`) with the field one (`plugin.manager.migrate.field`). The CCK one is just an empty class that extends the latter, so they're effectively equivalent.

I'll put up a PR.

**Comment by m4olivei** [comment]
@lokisho Could you take a look at #166? Let us know if that fixes your issue. I threw it together. I don't have a good setup to test that ATM.
