### ISSUE TITLE
Use the batch API for ingestion

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/media_mpx#24]
While it may not be strictly needed, it would help protect us from any small memory leaks over a long ingestion.

**Comment by deviantintegral** [comment]
I was really hoping to avoid this, but I've run an import for almost an hour and memory has gone from a start of ~120MB to almost 300MB, for ~23000 items. I'm sure we could eliminate some leaks, but there's enough code we don't control that we need to either batch or queue things.

I took a look at the D8 batch API and it's not improved much since D7. IOW, because it uses arrays for everything it's really easy for little mistakes to break things. While queues have a little more admin complexity, they also make it possible to run concurrently. Since I'll need to rework things, I am going towards the queue direction.

**Comment by juampynr** [comment]
Makes sense to me, @deviantintegral.

**Comment by geekygnr** [comment]
A PR has been made so I am closing this.
