### ISSUE TITLE
Fix class serialization errors when custom fields change

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/media_mpx#43]
On average, I'm seeing around 500ms response times from mpx to load a single media object. That adds up, especially when importing objects locally. I wanted a way to test importing without always hitting mpx, so `\Drupal\media_mpx\DataObjectImporter::setKeyValue` was added to store deserialized mpx objects in the key-value store.

I'd explicitly left this out of the cache system as I wanted to be able to rebuild caches _without_ clearing my locally stored mpx data.

However, this breaks in one critical case - during integration with custom fields. For example, let's say we create a `lullabot_mpx` module with a custom field implementation and turn it on. When we load the object, it will still have the stub `MissingCustomFieldsClass` set on the data. Or, lets say mpx doesn't change their object schema, but the mpx library adds a new method or internal field. We won't have that data, and FATALs result.

I see a few ways we could solve this:

1. Stop using the k/v store, and fall back to a straight cache implementation.
1. Instead of storing deserialized objects in k/v, store the literal mpx response data.
1. Do both, and store mpx response data in the cache (instead of serialized objects).
1. Create a "developer only" cache bin backend that is the opposite of the `\Drupal\Core\Cache\NullBackend` class - instead of never caching, it overrides `\Drupal\Core\Cache\CacheBackendInterface::deleteAll` to not delete anything. This would probably live as it's own developer module, and be enabled in `development.services.yml` and `settings.php`.

**Comment by juanolalla** [comment]
I was thinking in something like 3. We can use the normal cache as first place to go, and when cache is empty retrieve the data from the kv-store.

**Comment by deviantintegral** [comment]
By "both", I was meaning use the cache system, but store mpx response data instead of serialized objects. It sounds like you're thinking of loading from the cache first, and if that's a miss try the k/v store.

I think what I will do is start by just moving everything to cache, ignoring the performance hit for locals doing migration testing at the moment. That way, we are still able to implement any of the other options as we see fit.

**Comment by juanolalla** [comment]
:+1:
