### ISSUE TITLE
How to import mpx Players and media into Drupal 8

### ISSUE THREAD

**Issue by deepika740** [Lullabot/media_mpx#57]
After installing and enabling this module, I was able to set up mpx user and mpx account succesfully at admin/config/media/mpx but don't see the mpx players or videos getting imported. `drush ms` shows a d7 migration ID (d7_media_theplatform_mpx_source_field_storage) but nothing for d8. How can i import mpx players and media?

**Comment by deviantintegral** [comment]
You will also need to configure a media type - in general, most sites would have one media type for each mpx account.

At that point, you can pull in a single video if you have it's ID - the whole URL ending in `/Media/<number>`. If you want to pull ingest a batch of videos, you can use `drush media_mpx:import`. If you want to listen for updates for new and updated videos, you can use `drush media_mpx:listen`.

For migrations from a Drupal 7 site, in general migrations are named after the source they are from - in that case, the media_theplatform_mpx module. It will import accounts and media types for you, _except_ for the account password which you should probably configure in `settings.php`. Finally, we don't actually have a migration for players yet. While there is a media source plugin for players, we've yet to actually need that (instead, we configure the player in the field formatter), and we may remove that before a 1.0 release unless we find a need for it.

**Comment by deepika740** [comment]
Thank you for your quick reply. I was able to add an mpx video in Drupal after configuring a new media type with 'mpx Video player' field formatter. I can see it's thumbnail correctly but: 
1. it won't play the actual mpx video(published) whose ID we saved instead plays recently published videos, 
2. that too from another mpx account and not the account selected in admin/config/media/mpx/account/<myaccount> 

Have you by any chance noticed these issues.

**Comment by deviantintegral** [comment]
We're _just_ starting front-end development of the project we're on, so I haven't done much testing of playing videos yet. Can you double-check the generated iframe for the video, and see if it matches what you're expecting?

See https://github.com/Lullabot/mpx-php/blob/master/src/Player/Url.php for the class that generates the iframe source URL.

**Comment by deepika740** [comment]
The generated iframe says “release with PID u************p was not found; ignoring /select/" for the src https://player.theplatform.com/p/***/*********/select/u************p. I think that's the reason the player doesn't play the expected video but plays the recently published ones. Looking at thePlatform documentation, adding /media to this url(https://github.com/Lullabot/mpx-php/blob/master/src/Player/Url.php#L81) plays the expected video https://player.theplatform.com/p/***/*********/select/media/u************p.

**Comment by deviantintegral** [comment]
Thanks! It's interesting, I'd read the documentation that says:

> You can configure your player to display an additional piece of content that isn't in your default player feed by modifying the player's URL to reference a specific public URL. 

Which I interpreted as "start with the specified video, then continue with videos in the player's feed". I'll follow up with thePlatform to see if we can get clearer docs specified.

Care to file a pull request to fix this?

**Comment by deepika740** [comment]
sure will do.

**Comment by deepikakatta-natgeo** [comment]
@deviantintegral sorry for the delay. Opened a PR here -> https://github.com/Lullabot/mpx-php/pull/141
