### ISSUE TITLE
Track object's updated time when processing the notification queue

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/media_mpx#59]
When listening for notifications, we already filter out duplicate notifications. However, it turns out we still end up with many, many notifications for the same object over multiple notification responses from mpx (in contrast to duplicates within the same single notification). This makes processing the notification queue significantly slower than it should be.

To work around this, we should leverage our cached mpx data and check the last updated time before we process a notification. Something like:

1. When saving a notification, store the timestamp of the update.
1. Load the mpx object.
1. Check it's updated date. If it's older than the notification timestamp, go ahead and process the notification. Otherwise, discard the notification.

**Comment by geekygnr** [comment]
For testing this issue from @deviantintegral 

> You can use the video titled `Captain Lee Rosbach Calls the RHONY Boat Ride from Hell Drama "Overblown"` , it's full ID is `http://data.media.theplatform.com/media/data/Media/1342208067763`

**Comment by geekygnr** [comment]
Pull request made so I am going to close this.
