### ISSUE TITLE
Fix only storing one notification ID for all media bundles

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/media_mpx#63]
The notification ID stored in the state table should be per media type, not global for all media types.

https://github.com/Lullabot/media_mpx/blob/8.x-1.x/src/NotificationListener.php is where the code is that needs to be fixed.

**Comment by geekygnr** [comment]
@deviantintegral I think I have figured out what I need to do.

Would you like the notification id to include the media source plugin id as well as the media type id or is the media type id on its own sufficient?

**Comment by deviantintegral** [comment]
I think the media type is fine, since a media type's source can't change after it's been created.
